//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin_001 {
            get {
                return ResourceManager.GetString("Admin_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the author&apos;s name.
        /// </summary>
        internal static string Author_001 {
            get {
                return ResourceManager.GetString("Author_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name already exists, please change author name.
        /// </summary>
        internal static string Author_002 {
            get {
                return ResourceManager.GetString("Author_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successful authors.
        /// </summary>
        internal static string Author_003 {
            get {
                return ResourceManager.GetString("Author_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful authors.
        /// </summary>
        internal static string Author_004 {
            get {
                return ResourceManager.GetString("Author_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful authors.
        /// </summary>
        internal static string Author_005 {
            get {
                return ResourceManager.GetString("Author_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select on text of list data.
        /// </summary>
        internal static string Author_006 {
            get {
                return ResourceManager.GetString("Author_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the book&apos;s Title or Description or Author.
        /// </summary>
        internal static string Book_001 {
            get {
                return ResourceManager.GetString("Book_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not update the book when contributor not create.
        /// </summary>
        internal static string Book_002 {
            get {
                return ResourceManager.GetString("Book_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successful authors.
        /// </summary>
        internal static string Book_003 {
            get {
                return ResourceManager.GetString("Book_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful authors.
        /// </summary>
        internal static string Book_004 {
            get {
                return ResourceManager.GetString("Book_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful authors.
        /// </summary>
        internal static string Book_005 {
            get {
                return ResourceManager.GetString("Book_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the category&apos;s title.
        /// </summary>
        internal static string Category_001 {
            get {
                return ResourceManager.GetString("Category_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category title already exists, please change category title.
        /// </summary>
        internal static string Category_002 {
            get {
                return ResourceManager.GetString("Category_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successful category.
        /// </summary>
        internal static string Category_003 {
            get {
                return ResourceManager.GetString("Category_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful category.
        /// </summary>
        internal static string Category_004 {
            get {
                return ResourceManager.GetString("Category_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful category.
        /// </summary>
        internal static string Category_005 {
            get {
                return ResourceManager.GetString("Category_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select on text of list data.
        /// </summary>
        internal static string Category_006 {
            get {
                return ResourceManager.GetString("Category_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful Information.
        /// </summary>
        internal static string ChangePassword_001 {
            get {
                return ResourceManager.GetString("ChangePassword_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the information &apos;s password.
        /// </summary>
        internal static string ChangePassword_002 {
            get {
                return ResourceManager.GetString("ChangePassword_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation password is incorrect.
        /// </summary>
        internal static string ChangePassword_003 {
            get {
                return ResourceManager.GetString("ChangePassword_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect.
        /// </summary>
        internal static string ChangePassword_004 {
            get {
                return ResourceManager.GetString("ChangePassword_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change successful password.
        /// </summary>
        internal static string ChangePassword_005 {
            get {
                return ResourceManager.GetString("ChangePassword_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        internal static string Contributor_001 {
            get {
                return ResourceManager.GetString("Contributor_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        internal static string Login_001 {
            get {
                return ResourceManager.GetString("Login_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User_001 {
            get {
                return ResourceManager.GetString("User_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the user&apos;s username or password.
        /// </summary>
        internal static string User_002 {
            get {
                return ResourceManager.GetString("User_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User title already exists, please change username.
        /// </summary>
        internal static string User_003 {
            get {
                return ResourceManager.GetString("User_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add successful User.
        /// </summary>
        internal static string User_004 {
            get {
                return ResourceManager.GetString("User_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful User.
        /// </summary>
        internal static string User_005 {
            get {
                return ResourceManager.GetString("User_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete successful User.
        /// </summary>
        internal static string User_006 {
            get {
                return ResourceManager.GetString("User_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select on text of list data.
        /// </summary>
        internal static string User_007 {
            get {
                return ResourceManager.GetString("User_007", resourceCulture);
            }
        }
    }
}
